[[problems]]
name = "watermellon two"
description = "Can the watermellon be divided by 2 input is between 1 <= 100 there can be multiple input in multiple lines only seperated by new lines"
inputs = ["problems/watermellon/input.txt"]
outputs = ["problems/watermellon/output.txt"]

[[problems]]
name = "watermellon three"
description = "Can the watermellon be divided by 3 input is between 1 <= 100 there can be multiple input in multiple lines only seperated by new lines"
inputs = ["problems/watermellon/input2.txt"]
outputs = ["problems/watermellon/output2.txt"]
