[project]
name = "ttykata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "toml>=0.10.2",
    "prompt_toolkit>=3.0.0",
    "rich>=13.0.0",
]
